name: Build Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Kernel Source
        run: |
          git clone https://github.com/MotorolaMobilityLLC/kernel-mtk.git --depth=1 -b MMI-S3RWBS32.125-29-2-4-3 kernel-src
          cd kernel-src

      - name: Download Prebuilt GCC Toolchain
        run: |
          wget https://github.com/rajatgupta1998/platform_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9/archive/refs/heads/main.zip
          unzip main.zip
          mv platform_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9-main toolchain

      - name: Build Kernel
        run: |
          export PATH=$PWD/toolchain/bin:$PATH
          export CROSS_COMPILE=aarch64-linux-android-
          cd kernel-src
          make ARCH=arm64 ext_config/moto-k69v1_64-coful.config
          make -j$(nproc) ARCH=arm64
