name: Build Kernel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_kernel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment
        run: |
          # Install dependencies
          sudo apt update
          sudo apt install -y wget unzip build-essential

      - name: Download prebuilt toolchain
        run: |
          wget https://example.com/path/to/toolchain.tar.gz -O toolchain.tar.gz
          tar -xvzf toolchain.tar.gz
          export CROSS_COMPILE=$PWD/toolchain/bin/aarch64-linux-android-
          export PATH=$PATH:$PWD/toolchain/bin

      - name: Set up the kernel configuration
        run: |
          # Set the kernel configuration (Use your specific config file)
          cp arch/arm64/configs/ext_config/moto-k69v1_64-coful.config .config

      - name: Build the kernel
        run: |
          make ARCH=arm64 CROSS_COMPILE=$CROSS_COMPILE -j$(nproc)
        
      - name: Upload kernel image
        uses: actions/upload-artifact@v2
        with:
          name: kernel-image
          path: arch/arm64/boot/Image.gz-dtb
